### All configuration knobs are put here

# Your data directory
DATA_DIR = "./data/"

# declare labels
labels = [
  'asc',
  'beterleven1',
  'beterleven2',
  'beterleven3',
  'demeter',
  'eko',
  'fairtrade',
  'msc',
  'organic',
  'planetproof',
  # 'rfalliance', # Little data, enable when there is more data
  'utz',           
  'weidemelk',
  # 'vegan',      # Not that important for us right now
  # 'bio'         # AH Bio is not a true certificate
]

# used by: split_and_summary
split_and_csv_bool = True
reassign_csv_bool = True
preproces_bool = False
balance_certificates_bool = False
visualisation_bool = False

# used by: train, evaluate and predict
hue_distortion = 18
sat_distortion = 1.5
exp_distortion = 1.5
zoom_min = 0.5
zoom_max = 1.5
ratio_distortion = 0.7
train_obj_scale = 5
train_noobj_scale = 1
train_class_scale = 1

# used by: train
PRETRAINED_MODEL_PATH = DATA_DIR + "models/pretrained-yolov3.h5"
nr_epochs = 150
batch_size = 8

# used by: evaluate and predict (these files are generated by train)
MODEL_PATH = DATA_DIR + "models/detection_model-final-ex-057-loss-0003.253.h5"
JSON_PATH = DATA_DIR + "json/detection_config-final-ex-057.json"

